/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *label24;
  GtkWidget *notebook1;
  GtkWidget *fixed2;
  GtkWidget *treeview1;
  GtkWidget *entry1;
  GtkWidget *button1;
  GtkWidget *label6;
  GtkWidget *label1;
  GtkWidget *fixed3;
  GtkWidget *entry_parking_id;
  GtkWidget *entry_location;
  GtkWidget *ajout_zone;
  GtkWidget *label9;
  GtkWidget *label8;
  GtkWidget *datenaissance;
  GtkWidget *Pr__nom;
  GtkWidget *Nom;
  GtkWidget *zone_A;
  GSList *zone_A_group = NULL;
  GtkWidget *zone_b;
  GtkWidget *zone_c;
  GtkWidget *horaire_1;
  GtkWidget *horaire_2;
  GtkWidget *horaire_3;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *button_add_parking;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label25;
  GtkWidget *label2;
  GtkWidget *fixed4;
  GtkWidget *entry_modify_parking_id;
  GtkWidget *entry_modify_location;
  GtkWidget *treeview2;
  GtkWidget *Modifier_zone_de_travail;
  GtkWidget *combo_status_2;
  GtkWidget *Modifier_horaire;
  GtkWidget *label10;
  GtkWidget *label14;
  GtkWidget *button_update_parking;
  GtkWidget *Infos;
  GtkWidget *Refresh;
  GtkWidget *label3;
  GtkWidget *fixed6;
  GtkWidget *Supprimer;
  GtkWidget *supp_id_agent;
  GtkWidget *entry2;
  GtkWidget *button_refresh_stats;
  GtkWidget *Suppression_agent;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  label24 = gtk_label_new (_("ADMIN "));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed1), label24, 368, 8);
  gtk_widget_set_size_request (label24, 112, 40);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 0, 48);
  gtk_widget_set_size_request (notebook1, 904, 400);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1, 48, 64);
  gtk_widget_set_size_request (treeview1, 416, 256);
  gtk_widget_set_extension_events (treeview1, GDK_EXTENSION_EVENTS_ALL);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (treeview1), TRUE);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1, 512, 128);
  gtk_widget_set_size_request (entry1, 312, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  button1 = gtk_button_new_from_stock ("gtk-media-play");
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed2), button1, 672, 256);
  gtk_widget_set_size_request (button1, 144, 40);

  label6 = gtk_label_new (_("Identifiant :       Horaires :         Zone :"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 0, 16);
  gtk_widget_set_size_request (label6, 344, 48);

  label1 = gtk_label_new (_("Afficher :"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  entry_parking_id = gtk_entry_new ();
  gtk_widget_show (entry_parking_id);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_parking_id, 312, 32);
  gtk_widget_set_size_request (entry_parking_id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_parking_id), 8226);

  entry_location = gtk_entry_new ();
  gtk_widget_show (entry_location);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_location, 312, 80);
  gtk_widget_set_size_request (entry_location, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_location), 8226);

  ajout_zone = gtk_label_new (_("Zone de Travail Assign\303\251e :"));
  gtk_widget_show (ajout_zone);
  gtk_fixed_put (GTK_FIXED (fixed3), ajout_zone, 48, 328);
  gtk_widget_set_size_request (ajout_zone, 184, 32);

  label9 = gtk_label_new (_("Horaires De Travail :"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed3), label9, 48, 256);
  gtk_widget_set_size_request (label9, 184, 64);

  label8 = gtk_label_new (_("Identifiant d'Agent :"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed3), label8, 88, 200);
  gtk_widget_set_size_request (label8, 96, 48);

  datenaissance = gtk_label_new (_("Date De Naissance : "));
  gtk_widget_show (datenaissance);
  gtk_fixed_put (GTK_FIXED (fixed3), datenaissance, 56, 144);
  gtk_widget_set_size_request (datenaissance, 152, 40);

  Pr__nom = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (Pr__nom);
  gtk_fixed_put (GTK_FIXED (fixed3), Pr__nom, 88, 80);
  gtk_widget_set_size_request (Pr__nom, 104, 48);

  Nom = gtk_label_new (_("Nom d'Agent :"));
  gtk_widget_show (Nom);
  gtk_fixed_put (GTK_FIXED (fixed3), Nom, 64, 24);
  gtk_widget_set_size_request (Nom, 152, 48);

  zone_A = gtk_radio_button_new_with_mnemonic (NULL, _("Zone A :"));
  gtk_widget_show (zone_A);
  gtk_fixed_put (GTK_FIXED (fixed3), zone_A, 296, 328);
  gtk_widget_set_size_request (zone_A, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (zone_A), zone_A_group);
  zone_A_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (zone_A));

  zone_b = gtk_radio_button_new_with_mnemonic (NULL, _("Zone B :"));
  gtk_widget_show (zone_b);
  gtk_fixed_put (GTK_FIXED (fixed3), zone_b, 488, 328);
  gtk_widget_set_size_request (zone_b, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (zone_b), zone_A_group);
  zone_A_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (zone_b));

  zone_c = gtk_radio_button_new_with_mnemonic (NULL, _("Zone C :"));
  gtk_widget_show (zone_c);
  gtk_fixed_put (GTK_FIXED (fixed3), zone_c, 712, 328);
  gtk_widget_set_size_request (zone_c, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (zone_c), zone_A_group);
  zone_A_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (zone_c));

  horaire_1 = gtk_radio_button_new_with_mnemonic (NULL, _("8h - 15h"));
  gtk_widget_show (horaire_1);
  gtk_fixed_put (GTK_FIXED (fixed3), horaire_1, 296, 280);
  gtk_widget_set_size_request (horaire_1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (horaire_1), zone_A_group);
  zone_A_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (horaire_1));

  horaire_2 = gtk_radio_button_new_with_mnemonic (NULL, _("15h - 22h"));
  gtk_widget_show (horaire_2);
  gtk_fixed_put (GTK_FIXED (fixed3), horaire_2, 496, 280);
  gtk_widget_set_size_request (horaire_2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (horaire_2), zone_A_group);
  zone_A_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (horaire_2));

  horaire_3 = gtk_radio_button_new_with_mnemonic (NULL, _("22h - 08h"));
  gtk_widget_show (horaire_3);
  gtk_fixed_put (GTK_FIXED (fixed3), horaire_3, 712, 280);
  gtk_widget_set_size_request (horaire_3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (horaire_3), zone_A_group);
  zone_A_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (horaire_3));

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed3), entry6, 312, 208);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed3), entry7, 312, 144);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  button_add_parking = gtk_button_new ();
  gtk_widget_show (button_add_parking);
  gtk_fixed_put (GTK_FIXED (fixed3), button_add_parking, 696, 120);
  gtk_widget_set_size_request (button_add_parking, 136, 48);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button_add_parking), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox1), label25, FALSE, FALSE, 0);

  label2 = gtk_label_new (_("Ajouter : "));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  entry_modify_parking_id = gtk_entry_new ();
  gtk_widget_show (entry_modify_parking_id);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_modify_parking_id, 224, 88);
  gtk_widget_set_size_request (entry_modify_parking_id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modify_parking_id), 8226);

  entry_modify_location = gtk_entry_new ();
  gtk_widget_show (entry_modify_location);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_modify_location, 224, 152);
  gtk_widget_set_size_request (entry_modify_location, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modify_location), 8226);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview2, 464, 64);
  gtk_widget_set_size_request (treeview2, 344, 208);

  Modifier_zone_de_travail = gtk_label_new (_("modifier zone de travail"));
  gtk_widget_show (Modifier_zone_de_travail);
  gtk_fixed_put (GTK_FIXED (fixed4), Modifier_zone_de_travail, 16, 216);
  gtk_widget_set_size_request (Modifier_zone_de_travail, 184, 32);

  combo_status_2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combo_status_2);
  gtk_fixed_put (GTK_FIXED (fixed4), combo_status_2, 224, 216);
  gtk_widget_set_size_request (combo_status_2, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_status_2), _("Zone A"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_status_2), _("Zone B"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_status_2), _("Zone C"));

  Modifier_horaire = gtk_label_new (_("modifier horaire"));
  gtk_widget_show (Modifier_horaire);
  gtk_fixed_put (GTK_FIXED (fixed4), Modifier_horaire, 24, 152);
  gtk_widget_set_size_request (Modifier_horaire, 160, 24);

  label10 = gtk_label_new (_("modifier Identifiant :"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed4), label10, 32, 88);
  gtk_widget_set_size_request (label10, 152, 24);

  label14 = gtk_label_new (_("Modifier Agent"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed4), label14, 104, 24);
  gtk_widget_set_size_request (label14, 224, 32);

  button_update_parking = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_show (button_update_parking);
  gtk_fixed_put (GTK_FIXED (fixed4), button_update_parking, 176, 272);
  gtk_widget_set_size_request (button_update_parking, 144, 48);

  Infos = gtk_label_new (_("    Agent ID        Zone de travail     Horaire    "));
  gtk_widget_show (Infos);
  gtk_fixed_put (GTK_FIXED (fixed4), Infos, 432, 16);
  gtk_widget_set_size_request (Infos, 360, 48);

  Refresh = gtk_button_new_from_stock ("gtk-yes");
  gtk_widget_show (Refresh);
  gtk_fixed_put (GTK_FIXED (fixed4), Refresh, 544, 280);
  gtk_widget_set_size_request (Refresh, 136, 45);

  label3 = gtk_label_new (_("Modifier :"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label3);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  Supprimer = gtk_label_new (_("Supprimer Agent :"));
  gtk_widget_show (Supprimer);
  gtk_fixed_put (GTK_FIXED (fixed6), Supprimer, 256, 32);
  gtk_widget_set_size_request (Supprimer, 256, 80);

  supp_id_agent = gtk_label_new (_("Identifiant Agent :"));
  gtk_widget_show (supp_id_agent);
  gtk_fixed_put (GTK_FIXED (fixed6), supp_id_agent, 48, 160);
  gtk_widget_set_size_request (supp_id_agent, 240, 72);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed6), entry2, 344, 176);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  button_refresh_stats = gtk_button_new_from_stock ("gtk-delete");
  gtk_widget_show (button_refresh_stats);
  gtk_fixed_put (GTK_FIXED (fixed6), button_refresh_stats, 744, 272);
  gtk_widget_set_size_request (button_refresh_stats, 104, 48);

  Suppression_agent = gtk_label_new (_("Supprimer :"));
  gtk_widget_show (Suppression_agent);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), Suppression_agent);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "columns_changed",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "move_cursor",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) zone_A, "clicked",
                    G_CALLBACK (on_zone_A_clicked),
                    NULL);
  g_signal_connect ((gpointer) zone_b, "clicked",
                    G_CALLBACK (on_zone_b_clicked),
                    NULL);
  g_signal_connect ((gpointer) zone_c, "clicked",
                    G_CALLBACK (on_zone_c_clicked),
                    NULL);
  g_signal_connect ((gpointer) horaire_1, "clicked",
                    G_CALLBACK (on_horaire_1_clicked),
                    NULL);
  g_signal_connect ((gpointer) horaire_2, "clicked",
                    G_CALLBACK (on_horaire_2_clicked),
                    NULL);
  g_signal_connect ((gpointer) horaire_3, "clicked",
                    G_CALLBACK (on_horaire_3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_add_parking, "clicked",
                    G_CALLBACK (on_button_add_parking_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_update_parking, "clicked",
                    G_CALLBACK (on_button_update_parking_clicked),
                    NULL);
  g_signal_connect ((gpointer) Refresh, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_refresh_stats, "clicked",
                    G_CALLBACK (on_button_refresh_stats_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, label24, "label24");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window1, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window1, entry_parking_id, "entry_parking_id");
  GLADE_HOOKUP_OBJECT (window1, entry_location, "entry_location");
  GLADE_HOOKUP_OBJECT (window1, ajout_zone, "ajout_zone");
  GLADE_HOOKUP_OBJECT (window1, label9, "label9");
  GLADE_HOOKUP_OBJECT (window1, label8, "label8");
  GLADE_HOOKUP_OBJECT (window1, datenaissance, "datenaissance");
  GLADE_HOOKUP_OBJECT (window1, Pr__nom, "Pr__nom");
  GLADE_HOOKUP_OBJECT (window1, Nom, "Nom");
  GLADE_HOOKUP_OBJECT (window1, zone_A, "zone_A");
  GLADE_HOOKUP_OBJECT (window1, zone_b, "zone_b");
  GLADE_HOOKUP_OBJECT (window1, zone_c, "zone_c");
  GLADE_HOOKUP_OBJECT (window1, horaire_1, "horaire_1");
  GLADE_HOOKUP_OBJECT (window1, horaire_2, "horaire_2");
  GLADE_HOOKUP_OBJECT (window1, horaire_3, "horaire_3");
  GLADE_HOOKUP_OBJECT (window1, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window1, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (window1, button_add_parking, "button_add_parking");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, label25, "label25");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window1, entry_modify_parking_id, "entry_modify_parking_id");
  GLADE_HOOKUP_OBJECT (window1, entry_modify_location, "entry_modify_location");
  GLADE_HOOKUP_OBJECT (window1, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (window1, Modifier_zone_de_travail, "Modifier_zone_de_travail");
  GLADE_HOOKUP_OBJECT (window1, combo_status_2, "combo_status_2");
  GLADE_HOOKUP_OBJECT (window1, Modifier_horaire, "Modifier_horaire");
  GLADE_HOOKUP_OBJECT (window1, label10, "label10");
  GLADE_HOOKUP_OBJECT (window1, label14, "label14");
  GLADE_HOOKUP_OBJECT (window1, button_update_parking, "button_update_parking");
  GLADE_HOOKUP_OBJECT (window1, Infos, "Infos");
  GLADE_HOOKUP_OBJECT (window1, Refresh, "Refresh");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window1, Supprimer, "Supprimer");
  GLADE_HOOKUP_OBJECT (window1, supp_id_agent, "supp_id_agent");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, button_refresh_stats, "button_refresh_stats");
  GLADE_HOOKUP_OBJECT (window1, Suppression_agent, "Suppression_agent");

  return window1;
}

GtkWidget*
create_Espace_Administrateur (void)
{
  GtkWidget *Espace_Administrateur;
  GtkWidget *fixed7;
  GtkWidget *Espace_admin;
  GtkWidget *Gestion_des_Parkings;
  GtkWidget *gestion_agents;
  GtkWidget *gestion_services;
  GtkWidget *retour;
  GtkWidget *image2;
  GtkWidget *exiit;
  GtkWidget *image3;

  Espace_Administrateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Espace_Administrateur), _("Espace Administrateur "));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (Espace_Administrateur), fixed7);

  Espace_admin = gtk_label_new (_("Espace Administrateur :"));
  gtk_widget_show (Espace_admin);
  gtk_fixed_put (GTK_FIXED (fixed7), Espace_admin, 272, 24);
  gtk_widget_set_size_request (Espace_admin, 304, 80);

  Gestion_des_Parkings = gtk_button_new_with_mnemonic (_("Gestion Des Parkings :"));
  gtk_widget_show (Gestion_des_Parkings);
  gtk_fixed_put (GTK_FIXED (fixed7), Gestion_des_Parkings, 280, 144);
  gtk_widget_set_size_request (Gestion_des_Parkings, 312, 72);

  gestion_agents = gtk_button_new_with_mnemonic (_("Gestion Des Agents :"));
  gtk_widget_show (gestion_agents);
  gtk_fixed_put (GTK_FIXED (fixed7), gestion_agents, 280, 248);
  gtk_widget_set_size_request (gestion_agents, 312, 72);

  gestion_services = gtk_button_new_with_mnemonic (_("Gestion Des Services"));
  gtk_widget_show (gestion_services);
  gtk_fixed_put (GTK_FIXED (fixed7), gestion_services, 288, 368);
  gtk_widget_set_size_request (gestion_services, 312, 72);

  retour = gtk_button_new ();
  gtk_widget_show (retour);
  gtk_fixed_put (GTK_FIXED (fixed7), retour, 40, 448);
  gtk_widget_set_size_request (retour, 74, 29);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_container_add (GTK_CONTAINER (retour), image2);

  exiit = gtk_button_new ();
  gtk_widget_show (exiit);
  gtk_fixed_put (GTK_FIXED (fixed7), exiit, 776, 16);
  gtk_widget_set_size_request (exiit, 74, 29);

  image3 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_container_add (GTK_CONTAINER (exiit), image3);

  g_signal_connect ((gpointer) Gestion_des_Parkings, "clicked",
                    G_CALLBACK (on_Gestion_des_Parkings_clicked),
                    NULL);
  g_signal_connect ((gpointer) gestion_services, "clicked",
                    G_CALLBACK (on_gestion_services_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour, "clicked",
                    G_CALLBACK (on_retour_clicked),
                    NULL);
  g_signal_connect ((gpointer) exiit, "clicked",
                    G_CALLBACK (on_exiit_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Espace_Administrateur, Espace_Administrateur, "Espace_Administrateur");
  GLADE_HOOKUP_OBJECT (Espace_Administrateur, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (Espace_Administrateur, Espace_admin, "Espace_admin");
  GLADE_HOOKUP_OBJECT (Espace_Administrateur, Gestion_des_Parkings, "Gestion_des_Parkings");
  GLADE_HOOKUP_OBJECT (Espace_Administrateur, gestion_agents, "gestion_agents");
  GLADE_HOOKUP_OBJECT (Espace_Administrateur, gestion_services, "gestion_services");
  GLADE_HOOKUP_OBJECT (Espace_Administrateur, retour, "retour");
  GLADE_HOOKUP_OBJECT (Espace_Administrateur, image2, "image2");
  GLADE_HOOKUP_OBJECT (Espace_Administrateur, exiit, "exiit");
  GLADE_HOOKUP_OBJECT (Espace_Administrateur, image3, "image3");

  return Espace_Administrateur;
}

GtkWidget*
create_Authenification (void)
{
  GtkWidget *Authenification;
  GtkWidget *fixed8;
  GtkWidget *Login_auth;
  GtkWidget *label30;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *button12;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image4;
  GtkWidget *label31;

  Authenification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Authenification), _("Authentification"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (Authenification), fixed8);

  Login_auth = gtk_label_new (_("Login :"));
  gtk_widget_show (Login_auth);
  gtk_fixed_put (GTK_FIXED (fixed8), Login_auth, 80, 120);
  gtk_widget_set_size_request (Login_auth, 200, 64);

  label30 = gtk_label_new (_("Mot de Passe : "));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed8), label30, 96, 264);
  gtk_widget_set_size_request (label30, 192, 56);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed8), entry3, 368, 128);
  gtk_widget_set_size_request (entry3, 232, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed8), entry4, 368, 264);
  gtk_widget_set_size_request (entry4, 232, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed8), button12, 656, 384);
  gtk_widget_set_size_request (button12, 152, 53);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button12), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image4 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox2), image4, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("Se Connecter :"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox2), label31, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_button12_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Authenification, Authenification, "Authenification");
  GLADE_HOOKUP_OBJECT (Authenification, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (Authenification, Login_auth, "Login_auth");
  GLADE_HOOKUP_OBJECT (Authenification, label30, "label30");
  GLADE_HOOKUP_OBJECT (Authenification, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (Authenification, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (Authenification, button12, "button12");
  GLADE_HOOKUP_OBJECT (Authenification, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Authenification, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Authenification, image4, "image4");
  GLADE_HOOKUP_OBJECT (Authenification, label31, "label31");

  return Authenification;
}

